name: Run cypress test and publish report
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Init and run test 
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - run: npm ci
      - run: npm run test --browser chrome
        continue-on-error: true
      
      - name: Copy test execution screenshots
        run: |
          cp -r cypress/screenshots public/screenshots

      - name: Deploy cypress report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
